[keystone] improve keystone chart

diff --git a/charts/keystone/templates/configmap-etc.yaml b/charts/keystone/templates/configmap-etc.yaml
--- a/charts/keystone/templates/configmap-etc.yaml
+++ b/charts/keystone/templates/configmap-etc.yaml
@@ -4,216 +4,144 @@ metadata:
   name: keystone-etc
   namespace: {{ .Release.Namespace | quote }}
 data:
-  {{- $memcachedFullname := include "keystone.cacheHost" . }}
-  {{- $memcachedPort := include "keystone.cachePort" . | int }}
-  keystone.sh: |-
-    echo "
+  keystone.conf: |-
     [DEFAULT]
     debug = False
-    transport_url = rabbit://{{ include "keystone.rabbitmq.user" . }}:$RABBITMQ_PASSWORD@{{ include "keystone.rabbitmq.host" . }}:{{ include "keystone.rabbitmq.port" . }}
+    transport_url = {{ index .Values "openstack-dep" "openstackEnv" "rabbitmqUrl" }}
+    log_file = /var/log/kolla/keystone/keystone.log
     use_stderr = True
+
     [oslo_middleware]
     enable_proxy_headers_parsing = True
+
+    [database]
+    connection = mysql+pymysql://{{ include "keystone.databaseUser" . }}:{{ include "keystone.databasePassword" . }}@{{ index .Values "openstack-dep" "openstackEnv" "mariadbUrl" }}/{{ include "keystone.databaseName" . }}
+    connection_recycle_time = 10
+    max_pool_size = 1
+    max_retries = -1
+
     [token]
     revoke_by_id = False
     provider = fernet
     expiration = 86400
     allow_expired_window = 172800
+
     [fernet_tokens]
     max_active_keys = 3
+
     [cache]
-    backend = dogpile.cache.memcached
-    enabled = {{ index .Values "openstack-dep" "memcached" "enabled" }}
-    memcache_servers = {{ $memcachedFullname }}:{{  $memcachedPort }}
+    backend = oslo_cache.memcache_pool
+    enabled = True
+    memcache_servers = {{ index .Values "openstack-dep" "openstackEnv" "memcacheUrl" }}
+
     [oslo_messaging_notifications]
-    transport_url = rabbit://{{ include "keystone.rabbitmq.user" . }}:$RABBITMQ_PASSWORD@{{ include "keystone.rabbitmq.host" . }}:{{ include "keystone.rabbitmq.port" . }}
+    transport_url = {{ index .Values "openstack-dep" "openstackEnv" "rabbitmqUrl" }} 
     driver = messagingv2
     topics = barbican_notifications
-    [database]
-    connection = mysql+pymysql://{{ include "keystone.databaseUser" . }}:$KEYSTONE_DATABASE_PASSWORD@{{ include "keystone.databaseHost" . }}:{{ include "keystone.databasePort" . }}/{{ include "keystone.databaseName" . }}
-    connection_recycle_time = 10
-    max_pool_size = 1
-    max_retries = -1
-    " > /etc/keystone/keystone.conf
-  access_rules.json: |-
-    {}
-  logging.conf: |-
-    [formatter_context]
-    class = oslo_log.formatters.ContextFormatter
-    datefmt = %Y-%m-%d %H:%M:%S
-    [formatter_default]
-    datefmt = %Y-%m-%d %H:%M:%S
-    format = %(message)s
-    [formatters]
-    keys = context,default
-    [handler_null]
-    args = ()
-    class = logging.NullHandler
-    formatter = default
-    [handler_stderr]
-    args = (sys.stderr,)
-    class = StreamHandler
-    formatter = context
-    [handler_stdout]
-    args = (sys.stdout,)
-    class = StreamHandler
-    formatter = context
-    [handlers]
-    keys = stdout,stderr,null
-    [logger_amqp]
-    handlers = stderr
-    level = WARNING
-    qualname = amqp
-    [logger_amqplib]
-    handlers = stderr
-    level = WARNING
-    qualname = amqplib
-    [logger_boto]
-    handlers = stderr
-    level = WARNING
-    qualname = boto
-    [logger_eventletwsgi]
-    handlers = stderr
-    level = WARNING
-    qualname = eventlet.wsgi.server
-    [logger_keystone]
-    handlers = stdout
-    level = INFO
-    qualname = keystone
-    [logger_root]
-    handlers = null
-    level = WARNING
-    [logger_sqlalchemy]
-    handlers = stderr
-    level = WARNING
-    qualname = sqlalchemy
-    [loggers]
-    keys = root,keystone
-  policy.yaml: |-
-    
-  ports.conf: |-
-    ""
-  sso_callback_template.html: |-
-    <!DOCTYPE html>
-    <html xmlns="http://www.w3.org/1999/xhtml">
-      <head>
-        <title>Keystone WebSSO redirect</title>
-      </head>
-      <body>
-        <form id="sso" name="sso" action="$host" method="post">
-          Please wait...
-          <br/>
-          <input type="hidden" name="token" id="token" value="$token"/>
-          <noscript>
-            <input type="submit" name="submit_no_javascript" id="submit_no_javascript"
-                value="If your JavaScript is disabled, please click to continue"/>
-          </noscript>
-        </form>
-        <script type="text/javascript">
-          window.onload = function() {
-            document.forms['sso'].submit();
+  config.json: |-
+    {
+      "command": "/usr/bin/keystone-startup.sh",
+      "config_files": [
+          {
+              "source": "/var/lib/kolla/config_files/keystone-startup.sh",
+              "dest": "/usr/bin/keystone-startup.sh",
+              "owner": "root",
+              "perm": "0755"
+          },
+          {
+              "source": "/var/lib/kolla/config_files/keystone.conf",
+              "dest": "/etc/keystone/keystone.conf",
+              "owner": "keystone",
+              "perm": "0600"
+          },
+          {
+              "source": "/var/lib/kolla/config_files/wsgi-keystone.conf",
+              "dest": "/etc/apache2/conf-enabled/wsgi-keystone.conf",
+              "owner": "keystone",
+              "perm": "0600"
           }
-        </script>
-      </body>
-    </html>
-  mpm_event.conf: |-
-    <IfModule mpm_event_module>
-      ServerLimit         1024
-      StartServers        32
-      MinSpareThreads     32
-      MaxSpareThreads     256
-      ThreadsPerChild     25
-      MaxRequestsPerChild 128
-      ThreadLimit         720
-    </IfModule>
-  security.conf: |-
-    #
-    # Disable access to the entire file system except for the directories that
-    # are explicitly allowed later.
-    #
-    # This currently breaks the configurations that come with some web application
-    # Debian packages.
-    #
-    #<Directory />
-    #   AllowOverride None
-    #   Require all denied
-    #</Directory>
+      ],
+      "permissions": [
+          {
+              "path": "/var/log/kolla",
+              "owner": "keystone:kolla"
+          },
+          {
+              "path": "/var/log/kolla/keystone/keystone.log",
+              "owner": "keystone:keystone"
+          }
+      ]
+    }
+  keystone-startup.sh: |-
+    #!/bin/bash -x
+    set -o errexit
+    set -o pipefail
 
-    # Changing the following options will not really affect the security of the
-    # server, but might make attacks slightly more difficult in some cases.
+    FERNET_KEY_DIR="/etc/keystone/fernet-keys"
 
-    #
-    # ServerTokens
-    # This directive configures what you return as the Server HTTP response
-    # Header. The default is 'Full' which sends information about the OS-Type
-    # and compiled in modules.
-    # Set to one of:  Full | OS | Minimal | Minor | Major | Prod
-    # where Full conveys the most information, and Prod the least.
-    ServerTokens Prod
+    # Ensure Fernet keys are populated, check for 0 (staging) key
+    n=0
+    while [ ! -f "${FERNET_KEY_DIR}/0" ]; do
+        if [ $n -lt 36 ]; then
+            n=$(( n + 1 ))
+            echo "ERROR: Fernet keys have not been populated, rechecking in 5 seconds"
+            echo "DEBUG: ${FERNET_KEY_DIR} contents:"
+            ls -l ${FERNET_KEY_DIR}
+            sleep 5
+        else
+            echo "CRITICAL: Waited for 3 minutes - failing"
+            exit 1
+        fi
+    done
 
-    #
-    # Optionally add a line containing the server version and virtual host
-    # name to server-generated pages (internal error documents, FTP directory
-    # listings, mod_status and mod_info output etc., but not CGI generated
-    # documents or custom error documents).
-    # Set to "EMail" to also include a mailto: link to the ServerAdmin.
-    # Set to one of:  On | Off | EMail
-    ServerSignature Off
-
-    #
-    # Allow TRACE method
-    #
-    # Set to "extended" to also reflect the request body (only for testing and
-    # diagnostic purposes).
-    #
-    # Set to one of:  On | Off | extended
-    TraceEnable Off
-
-    #
-    # Forbid access to version control directories
-    #
-    # If you use version control systems in your document root, you should
-    # probably deny access to their directories. For example, for subversion:
-    #
-    #<DirectoryMatch "/\.svn">
-    #   Require all denied
-    #</DirectoryMatch>
-
-    #
-    # Setting this header will prevent MSIE from interpreting files as something
-    # else than declared by the content type in the HTTP headers.
-    # Requires mod_headers to be enabled.
-    #
-    #Header set X-Content-Type-Options: "nosniff"
-
-    #
-    # Setting this header will prevent other sites from embedding pages from this
-    # site as frames. This defends against clickjacking attacks.
-    # Requires mod_headers to be enabled.
-    #
-    #Header set X-Frame-Options: "sameorigin"
+    exec /usr/sbin/apache2 $@
   wsgi-keystone.conf: |-
     Listen 0.0.0.0:5000
+    Listen 0.0.0.0:35357
 
-    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
-    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
+    ServerSignature Off
+    ServerTokens Prod
+    TraceEnable off
 
-    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
-    CustomLog /dev/stdout combined env=!forwarded
-    CustomLog /dev/stdout proxy env=forwarded
+    ErrorLog "/var/log/kolla/keystone/apache-error.log"
+    <IfModule log_config_module>
+        CustomLog "/var/log/kolla/keystone/apache-access.log" common
+    </IfModule>
+
+    <Directory "/var/lib/kolla/venv/bin/">
+        <FilesMatch "^keystone-wsgi-(public|admin)$">
+            AllowOverride None
+            Options None
+            Require all granted
+        </FilesMatch>
+    </Directory>
 
     <VirtualHost *:5000>
-        WSGIDaemonProcess keystone-public processes=1 threads=1 user=keystone group=keystone display-name=%{GROUP}
+        WSGIDaemonProcess keystone-public processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP} python-path=/var/lib/kolla/venv/lib/python3.8/site-packages
         WSGIProcessGroup keystone-public
-        WSGIScriptAlias / /var/www/cgi-bin/keystone/keystone-wsgi-public
+        WSGIScriptAlias / /var/lib/kolla/venv/bin/keystone-wsgi-public
         WSGIApplicationGroup %{GLOBAL}
         WSGIPassAuthorization On
         <IfVersion >= 2.4>
           ErrorLogFormat "%{cu}t %M"
         </IfVersion>
-        ErrorLog /dev/stdout
+        ErrorLog "/var/log/kolla/keystone/keystone-apache-public-error.log"
+        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" logformat
+        CustomLog "/var/log/kolla/keystone/keystone-apache-public-access.log" logformat
 
-        SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
-        CustomLog /dev/stdout combined env=!forwarded
-        CustomLog /dev/stdout proxy env=forwarded
+    </VirtualHost>
+
+    <VirtualHost *:35357>
+        WSGIDaemonProcess keystone-admin processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP} python-path=/var/lib/kolla/venv/lib/python3.8/site-packages
+        WSGIProcessGroup keystone-admin
+        WSGIScriptAlias / /var/lib/kolla/venv/bin/keystone-wsgi-admin
+        WSGIApplicationGroup %{GLOBAL}
+        WSGIPassAuthorization On
+        <IfVersion >= 2.4>
+          ErrorLogFormat "%{cu}t %M"
+        </IfVersion>
+        ErrorLog "/var/log/kolla/keystone/keystone-apache-admin-error.log"
+        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" logformat
+        CustomLog "/var/log/kolla/keystone/keystone-apache-admin-access.log" logformat
+
     </VirtualHost>
